FROM apache/airflow:2.8.4-python3.10

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

USER airflow

RUN uv pip install --system --no-cache \
    "pymysql" \
    "kedro~=1.0.0" \
    "kedro-airflow" \
    "kedro-datasets[pandas-csvdataset]" \
    "pymongo" \
    "python-dotenv" \
    "nltk"
