site_name: FakeShield
docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.highlight
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Architecture Technique: index.md
