name: CI
on:
  push:
    branches: [ main, dev, ci ]
  pull_request:
    branches: [ main, dev, ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        make install-all
    - name: ruff check
      run: |
        make lint
    - name: Load all repo secrets as env vars
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: |
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "$SECRETS_CONTEXT" | jq -r "to_entries[] | \"\(.key)<<$EOF\n\(.value)\n$EOF\"" >> $GITHUB_ENV

    - name: pytest
      run: make test
